name: hello-world-flow
on: [push, pull_request]
jobs:
  Generate-Bins: 
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/Static/X86/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A Win32,
            arch: X86,
            build_paths: "build/Release/${{ github.workflow }}.exe",
            }
          - {
            name: "Windows/Static/X64/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
            arch: X64,
            build_paths: "build/Release/${{ github.workflow }}.exe",
            }
          - {
            name: "Ubuntu/18.04/Static/X64/Release",
            os: ubuntu-18.04,
            config: Release,
            cmake_extra_args: "-DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10",
            arch: X64,
            build_paths: "build/${{ github.workflow }}",
            }
          - {
            name: "MacOSX/Static/X64/Release",
            os: macos-10.15,
            config: Release,
            args: "",
            arch: X64,
            build_paths: "build/${{ github.workflow }}",
            }
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
      - name: build
        working-directory: ./build
        run: cmake --build . -j --config ${{ matrix.config.config }}
      - name: Test
        working-directory: ./build
        run: ctest -j -C ${{ matrix.config.config }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.config.arch }}-${{ github.ref_name }}-${{ github.repository_id }}-${{ github.run_number }}
          path: ${{ github.workspace }}/${{ matrix.config.build_paths }}

  Package-WindowsInstallers:
    needs: [Generate-Bins]
    runs-on: windows-latest
    steps:
      - name: Download project
        uses: actions/checkout@v2
      - name: Download EXE
        uses: actions/download-artifact@v3
        with:
          name: Windows-X64-${{ github.ref_name }}-${{ github.repository_id }}-${{ github.run_number }}
          path: ${{ github.workspace }}/${{ matrix.config.build_paths }}
      - name: Build MSI Installer
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-enable-automation: 'false'
          aip-path: ${{ github.workspace }}\HelloWorld_msi.aip
          aip-build-name: 'MSI'
          aip-package-name: HelloWorld.msi
          aip-output-dir:  ${{ github.workspace }}
          aip-commands: |
            SetVersion 0.1.1
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v2
        with:
          name: HelloWorld.msi
          path: ${{ github.workspace }}\HelloWorld.msi
      - name: Build EXE Installer
        uses: caphyon/advinst-github-action@v1.0
        with:
          advinst-enable-automation: 'false'
          aip-path: ${{ github.workspace }}\HelloWorld_exe.aip
          aip-build-name: 'EXE'
          aip-package-name: HelloWorld.exe
          aip-output-dir:  ${{ github.workspace }}
          aip-commands: |
            SetVersion 0.1.1
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v2
        with:
          name: HelloWorld.exe
          path: ${{ github.workspace }}\HelloWorld.exe
