name: hello-world-flow
on: [push, pull_request]
jobs:
  build: 
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows/Static/X86/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A Win32,
            upload_name: Win32,
            build_paths: "build/Release/${{ github.workflow }}.exe",
            }
          - {
            name: "Windows/Static/X64/Release",
            os: windows-2019,
            config: Release,
            args: -G "Visual Studio 16 2019" -A x64,
            upload_name: Win64,
            build_paths: "build/Release/${{ github.workflow }}.exe",
            }
          - {
            name: "Ubuntu/18.04/Static/X64/Release",
            os: ubuntu-18.04,
            config: Release,
            cmake_extra_args: "-DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10",
            upload_name: Ubuntu,
            build_paths: "build/${{ github.workflow }}",
            }
          - {
            name: "MacOSX/Static/X64/Release",
            os: macos-10.15,
            config: Release,
            args: "",
            upload_name: MacOSX,
            build_paths: "build/${{ github.workflow }}",
            }
    steps:
      - uses: actions/checkout@v2
      - name: Create Work Dir
        run: mkdir build
      - name: Configure
        working-directory: ./build
        run: |
          cmake .. ${{ matrix.config.cmake_extra_args }} -DCMAKE_BUILD_TYPE=${{ matrix.config.config }}
      - name: build
        working-directory: ./build
        run: cmake --build . -j --config ${{ matrix.config.config }}
      - name: Test
        working-directory: ./build
        run: ctest -j -C ${{ matrix.config.config }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.upload_name }}-${{ runner.os }}-${{ runner.arch }}-${{ github.run_number }}
          path: ${{ github.workspace }}/${{ matrix.config.build_paths }}
